# Generated by Django 5.1 on 2024-10-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.ManyToManyField(related_name="posts", to="blog.category"),
        ),
    ]
