# Generated by Django 5.1 on 2024-10-07 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="technologies",
            name="image",
        ),
    ]
