# Generated by Django 5.1 on 2024-10-07 22:56
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_remove_technologies_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Formation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        max_length=100, verbose_name="Intitulé de la formation"
                    ),
                ),
                (
                    "trainer",
                    models.CharField(max_length=100, verbose_name="Institution"),
                ),
                (
                    "duration",
                    models.CharField(
                        max_length=50, verbose_name="Durée de la formation"
                    ),
                ),
                (
                    "date_started",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de debut"
                    ),
                ),
                (
                    "date_completed",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'achèvement"
                    ),
                ),
                (
                    "certificate",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="certificates/",
                        verbose_name="Certificat",
                    ),
                ),
            ],
        ),
    ]
