# Generated by Django 5.1 on 2024-11-17 11:11
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_softskill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formation",
            name="date_started",
            field=models.DateField(blank=True, null=True, verbose_name="Date de début"),
        ),
        migrations.AlterField(
            model_name="imageproject",
            name="catption",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Description de l'image (facultatif)",
            ),
        ),
        migrations.AlterField(
            model_name="projects",
            name="status",
            field=models.CharField(
                choices=[("1", "En cours"), ("2", "Réalisé"), ("3", "En production")],
                default="1",
                max_length=20,
            ),
        ),
    ]
